# Change these first
owner: renzoalis # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: WEB
    url: https://oceba.gba.gov.ar
    expectedStatusCodes:
     - 200
     - 201
     - 404
     - 0
  - name: Intranet
    url: https://oceba.gba.gov.ar/intranet
    expectedStatusCodes:
     - 200
     - 201
     - 404
     - 0
  - name: Extranet
    url: https://oceba.gba.gov.ar/extranet
    expectedStatusCodes:
     - 200
     - 201
     - 404
     - 0
  - name: Servidor de Archivos
    url: https://oceba.gba.gov.ar/intranet/reclamos/adjuntos/3/seia-1638550850.png
    
assignees:
  - renzoalis

status-website:
  theme: light
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://devgam.s3.sa-east-1.amazonaws.com/clientes/devgam/logo.png
  name: Status
  introTitle: "Estado de los servicios del Organismo"
  introMessage: En el tablero inferior se detalla el estado de los servicios. Si un servicio se cae, se notifica via mail.
  navbar:
    - title: Status
      href: /
    - title: Web
      href: https://dev-gam.com.ar

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
